spring.application.name=LearnJobPortal2026B01
#spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb+srv://phucdn:Phucdn.2601@cluster0.htx3e.mongodb.net/LSpringJobPlat2026B01?retryWrites=true&w=majority
#spring.data.mongodb.uri=mongodb://phucdn:phucdn@localhost:27017/LSpringJobPlat2026B01?authSource=admin&authMechanism=SCRAM-SHA-256
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=LSpringJobPlat2026B01
spring.data.mongodb.username=phucdn
spring.data.mongodb.password=phucdn
spring.data.mongodb.authentication-database=admin
springdoc.api-docs.path=/api-docs