spring.application.name=LearnJobPortal2026MysqlB02

spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_5VDuykkC
spring.datasource.username=u_CZoD5U
spring.datasource.password=xRGsmlyIwXv6

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs