spring.application.name=LearnJobPortal2026MysqlB02

spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_S9Nr5VZG
spring.datasource.username=u_22zOfp
spring.datasource.password=4GnECwvYWp8U

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs

# Email properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lnslbscl3@gmail.com
spring.mail.password=ossterkctzrgsgal
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties..mail.smtp.starttls.enable=true

USER_FOUND=User has registered already.
USER_NOT_FOUND=User is not registered already.
INVALID_CREDENTIALS=INVALID CREDENTIALS

OTP_NOT_FOUND=OTP is expired.
OTP_INCORRECT=OTP is incorrect.