package com.phucdn.jobportal.utility;

public class Data {
	public static String getMessageBody(String otp, String name) {
		String htmlContentString = "<!DOCTYPE html>\n"
				+ "<html lang=\"en\">\n"
				+ "<head>\n"
				+ "<meta charset=\"UTF-8\">\n"
				+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
				+ "<title>OTP Verification</title>\n"
				+ "<style>\n"
				+ "    body {\n"
				+ "        margin: 0;\n"
				+ "        padding: 0;\n"
				+ "        background-color: #f4f4f4;\n"
				+ "        font-family: Arial, Helvetica, sans-serif;\n"
				+ "    }\n"
				+ "\n"
				+ "    .container {\n"
				+ "        max-width: 600px;\n"
				+ "        margin: 40px auto;\n"
				+ "        background-color: #ffffff;\n"
				+ "        border-radius: 8px;\n"
				+ "        overflow: hidden;\n"
				+ "        box-shadow: 0 2px 10px rgba(0,0,0,0.1);\n"
				+ "    }\n"
				+ "\n"
				+ "    .header {\n"
				+ "        background-color: #2563eb;\n"
				+ "        color: white;\n"
				+ "        text-align: center;\n"
				+ "        padding: 30px 20px;\n"
				+ "    }\n"
				+ "\n"
				+ "    .header h1 {\n"
				+ "        margin: 0;\n"
				+ "        font-size: 24px;\n"
				+ "    }\n"
				+ "\n"
				+ "    .content {\n"
				+ "        padding: 40px 30px;\n"
				+ "        color: #333333;\n"
				+ "        line-height: 1.6;\n"
				+ "    }\n"
				+ "\n"
				+ "    .otp-box {\n"
				+ "        margin: 30px auto;\n"
				+ "        text-align: center;\n"
				+ "    }\n"
				+ "\n"
				+ "    .otp-code {\n"
				+ "        display: inline-block;\n"
				+ "        background-color: #f8fafc;\n"
				+ "        border: 2px dashed #2563eb;\n"
				+ "        color: #2563eb;\n"
				+ "        font-size: 32px;\n"
				+ "        font-weight: bold;\n"
				+ "        letter-spacing: 8px;\n"
				+ "        padding: 15px 30px;\n"
				+ "        border-radius: 8px;\n"
				+ "    }\n"
				+ "\n"
				+ "    .warning {\n"
				+ "        background-color: #fff7ed;\n"
				+ "        border-left: 4px solid #f97316;\n"
				+ "        padding: 15px;\n"
				+ "        margin-top: 25px;\n"
				+ "        color: #9a3412;\n"
				+ "        font-size: 14px;\n"
				+ "    }\n"
				+ "\n"
				+ "    .footer {\n"
				+ "        background-color: #f8fafc;\n"
				+ "        padding: 20px;\n"
				+ "        text-align: center;\n"
				+ "        font-size: 13px;\n"
				+ "        color: #666666;\n"
				+ "    }\n"
				+ "\n"
				+ "    .footer a {\n"
				+ "        color: #2563eb;\n"
				+ "        text-decoration: none;\n"
				+ "    }\n"
				+ "\n"
				+ "    @media screen and (max-width: 600px) {\n"
				+ "        .content {\n"
				+ "            padding: 25px 20px;\n"
				+ "        }\n"
				+ "\n"
				+ "        .otp-code {\n"
				+ "            font-size: 24px;\n"
				+ "            letter-spacing: 4px;\n"
				+ "            padding: 12px 20px;\n"
				+ "        }\n"
				+ "    }\n"
				+ "</style>\n"
				+ "</head>\n"
				+ "<body>\n"
				+ "\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
				+ "<tr>\n"
				+ "<td>\n"
				+ "\n"
				+ "<div class=\"container\">\n"
				+ "\n"
				+ "    <div class=\"header\">\n"
				+ "        <h1>Your Company Name</h1>\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div class=\"content\">\n"
				+ "\n"
				+ "        <h2>OTP Verification</h2>\n"
				+ "\n"
				+ "        <p>Hello " + name +" ,</p>\n"
				+ "\n"
				+ "        <p>\n"
				+ "            We received a request to verify your account. Please use the following\n"
				+ "            One-Time Password (OTP) to complete the verification process:\n"
				+ "        </p>\n"
				+ "\n"
				+ "        <div class=\"otp-box\">\n"
				+ "            <div class=\"otp-code\">\n"
				+ "                " + otp + "\n"
				+ "            </div>\n"
				+ "        </div>\n"
				+ "\n"
				+ "        <p>\n"
				+ "            This code will expire in <strong>10 minutes</strong>.\n"
				+ "        </p>\n"
				+ "\n"
				+ "        <p>\n"
				+ "            If you did not request this code, please ignore this email or contact our support team immediately.\n"
				+ "        </p>\n"
				+ "\n"
				+ "        <div class=\"warning\">\n"
				+ "            <strong>Security Notice:</strong><br>\n"
				+ "            Never share your OTP with anyone. Our team will never ask for your OTP by email, phone, or chat.\n"
				+ "        </div>\n"
				+ "\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div class=\"footer\">\n"
				+ "        <p>\n"
				+ "            © 2026 Your Company Name. All rights reserved.\n"
				+ "        </p>\n"
				+ "        <p>\n"
				+ "            Need help?\n"
				+ "            <a href=\"https://your-company.com/support\">Contact Support</a>\n"
				+ "        </p>\n"
				+ "    </div>\n"
				+ "\n"
				+ "</div>\n"
				+ "\n"
				+ "</td>\n"
				+ "</tr>\n"
				+ "</table>\n"
				+ "\n"
				+ "</body>\n"
				+ "</html>";
		
		return htmlContentString;
	}
	
	
}
