spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:sqlserver://localhost:1456;databaseName=learn-java-spring-daily-store-pro-b01;encrypt=false
spring.datasource.username=sa
spring.datasource.password=12345678A@
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8082
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB