spring.application.name=prac-spring-mc-ecom-2025-b01-product-service
spring.data.mongodb.uri=mongodb+srv://phucdn:PhucdnP@cluster0.htx3e.mongodb.net/pracspring2025EcProductService?retryWrites=true&w=majority
server.port=8081