spring.application.name=l-sp-3-pos-system-2025-b01-be

server.port=5000

spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_prac-spring-mc-ecom-2025-b01-order-service
spring.datasource.username=freedb_phucdn2601
spring.datasource.password=2yk2vyH@&YynCY8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true