version: '3.8'

services:
  dev-db:
    image: postgres:15
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=learn_prac_spring_nvc_2024_b01
    volumes:
      - dev-db:/var/lib/postgresql/data
    
volumes:
  dev-db: